name: publish-docker-image

on:
    push:
        branches:
            - main

jobs:
    publish-docker-image-on-github-cr:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Login to GitHub Container Registry (GHCR)
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push Docker Image to GHCR
              run: |
                  docker build -t ghcr.io/satyam-malviya/portfolio:latest .
                  docker push ghcr.io/satyam-malviya/portfolio:latest

    publish-docker-image-on-dockerhub:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: "satyam-malviya"
                  password: ${{ secrets.DOCKERHUB }}

            - name: Build and Push Docker Image to DockerHub
              run: |
                  docker build -t satyam-malviya/portfolio:latest .
                  docker push satyam-malviya/portfolio:latest
